version: '3'

services:

  postgres:
    container_name: postgres_container
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./imperia_db.sql:/docker-entrypoint-initdb.d/imperia_db.sql
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./DatosPrueba/caracteristicas_puntos_de_venta.csv:/docker-entrypoint-initdb.d/caracteristicas_puntos_de_venta.csv
      - ./DatosPrueba/caracteristicas_productos.csv:/docker-entrypoint-initdb.d/caracteristicas_productos.csv
      - ./DatosPrueba/caracteristicas_clientes.csv:/docker-entrypoint-initdb.d/caracteristicas_clientes.csv
        
 
